### ISSUE TITLE
Front-end 404 after installing

### ISSUE THREAD

**Issue by halyearzero** [langchain-ai/langsmith-sdk#168]
Hello,

I cannot seem to install this LangSmith locally and have an operational server.

No problems indicated when starting:

![image](https://github.com/langchain-ai/langsmith-sdk/assets/140323441/bf3ae442-a2ea-4a6a-8dbb-05b8a0ee3c1a)

Logs:

![image](https://github.com/langchain-ai/langsmith-sdk/assets/140323441/a0d3d36b-4ac6-4004-bd52-91203968cbd6)

Front-end:

![image](https://github.com/langchain-ai/langsmith-sdk/assets/140323441/45cee9fa-29a3-485d-8f01-1251fcff181f)

Is there some initialization procedure that I am missing?  I have also tried to send traces but receive messages regarding internal server errors.

Any help would be much appreciated.

**Comment by hinthornw** [comment]
Will investigate

**Comment by hinthornw** [comment]
@halyearzero should be fixed now. Could you try again?

**Comment by halyearzero** [comment]
instead of install with `pip install langsmith` I cloned the repo and installed via `pip install -e .`.  I'm still getting the error.

**Comment by hinthornw** [comment]
Is this the case if you run `langsmith stop` then restart with `langsmith start` ? What does it show if you run `langsmith env`?

**Comment by hinthornw** [comment]
Going to close as stale for now. Let me know if you still have issues
